### ISSUE TITLE
Vagrant login should be present to use this vagrant

### ISSUE THREAD

**Issue by BenoitLeveque** [Elao/symfony-standard#26]
vagrant : 1.6.5
vagrant plugins:
- vagrant-cachier (1.2.0)
- vagrant-hostmanager (1.5.0)
- vagrant-share (1.1.3, system)

```
$ vagrant        
/Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:8:in `rescue in <encoded>': vagrant-share can't be installed without vagrant login (RuntimeError)
	from /Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:5:in `<encoded>'
	from /Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:16:in `RGLoader_load'
	from /Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:16:in `<top (required)>'
	from /Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share.rb:23:in `require'
	from /Users/Benoit/.vagrant.d/gems/gems/vagrant-share-1.1.3/lib/vagrant-share.rb:23:in `block in <class:Plugin>'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:75:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:75:in `block (2 levels) in help'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:48:in `block in each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:47:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/registry.rb:47:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:69:in `block in help'
	from /Applications/Vagrant/embedded/lib/ruby/2.0.0/optparse.rb:885:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:57:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:57:in `help'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:32:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

**Comment by nervo** [comment]
What do you mean by "this vagrant" ?

**Comment by benji07** [comment]
We only need to add The vagrant-login plugin to The required plugin (it allo to download The box from vagrant cloud)

Envoyé de mon iPhone

**Comment by nervo** [comment]
What is this "required" plugin ? Cachier ?  Sorry, i don't get it :)
And by the way, you don't need additionnal plugin to download boxes on atlas (formelery vagrant cloud). Or i miss something there...

**Comment by benji07** [comment]
You need vagrant-login which is not installed by default anymore

**Comment by BenoitLeveque** [comment]
i only have this issue with a clean install version of 1.6.5, when i update vagrant to the latest version (1.7.2) i don't have the issue anymore

**Comment by nervo** [comment]
Well, i guess you have your answer :)

**Comment by BenoitLeveque** [comment]
in the readme i saw

```
Requirements

Vagrant 1.6.5+
```

**Comment by nervo** [comment]
I guess we know what to do :)

**Comment by benji07** [comment]
close by #27
